#!/bin/sh

# Automatically set up issue and pull request labels for GitHub repositories

printf "Repository name: "
read -r repository

printf "GitHub username: "
read -r username

printf "GitHub password: "
read -rs password
printf "\n"

account="$username"

printf "Is the repository owned by an organisation? [y/N] "
read -r if_org

if [ "$if_org" = "y" ] || [ "$if_org" = "Y" ]
then
    printf "GitHub organisation: "
    read -r organisation

    account="$organisation"
fi

url="https://api.github.com/repos/${account}/${repository}/labels"

curl -u "${username}:${password}" -X POST -d '{"name": "blocked", "color": "fef2c0", "description": "Waiting for another issue to be resolved"}' "$url"
curl -u "${username}:${password}" -X POST -d '{"name": "critical", "color": "000000", "description": "This needs fixing urgently"}' "$url"
curl -u "${username}:${password}" -X POST -d '{"name": "documentation", "color": "c5def5", "description": "Related to documentation and translation"}' "$url"
curl -u "${username}:${password}" -X POST -d '{"name": "priority", "color": "006b75", "description": "This is of high importance"}' "$url"
