#!/bin/sh

# FIXME only edit the staged copy of the file

for file in $(git diff --staged --name-only)
do
    attr="$(git check-attr 'trim-trailing-whitespace' -- "$file"
        | awk '{print $NF}')"

    if [ $attr = "set" ]
    then
        sed 's/\s\+$//' "$file" > "${file}-ascribe.tmp"
        if [ $? = 0 ]
        then
            mv "${file}-ascribe.tmp" "$file"
            # TODO: git stage file
        else
            echo "Failed to trim trailing whitespace from '$file'"
            exit 1
        fi
    fi
done

# Check for whitespace errors
# exec git diff-index --check --cached $against --
